### PR TITLE
#2: support stacked icons

### LINKED ISSUE #2: [Feature Request]: support stack
Thanks for the awesome work. Just wondering if possible to support stacked icons?

### PR DESCRIPTION
**Pull request by trung**
fixes #2 

I think it'd be better to change the background color to transparent as most users want that way.

### CODE REVIEW

**Comment by devgg** [comment]
Thanks for the PR. I have a few issues with style and functionality. Things that should be changed:

- deselecting the stacked icon should remove the icon
- ability to select the icon that you want to edit
   maybe add a list of icons that is clickable so you can stack multiple
- use the same style for the new text as the rest of the application uses

If you don't have time I will try to look into it this or next week
Cheers!

**Comment by trung** [comment]
Regarding 2), although it's good have multiple I think 2 is just enough for this. The current flow is simple, select 1st icon if stacked, second select is the stacked one. It's consistent with the idea of click and change from the beginning.

Agreed with 1 and 3, i can make changes.

**Comment by trung** [comment]
made 1) and 3), please review

**Comment by devgg** [comment]
Thanks for the updates. I think in 1) the frame should immediately redraw once the deselection takes place. And when you select the second icon again the same icon should reappear.

**Comment by trung** [comment]
I fixed the deselection issue
> And when you select the second icon again the same icon should reappear.
Not sure what you mean?

**Comment by devgg** [comment]
So I did some refining. Please take a look if this works for you.
PS: I was on an old computer and I think the old git version messed up the commit (files changed shows everything).

**Comment by trung** [comment]
Thanks. LGTM

**Pull request merged**
